- hosts: client
  become: yes
  roles:
    - ansible-role-docker
    - ansible-role-java
    #- gantsign.golang

- hosts: all
  become: yes
  roles:
    - ansible-role-consul
    - ansible-role-nomad

- hosts: server
  become: yes
  roles:
    - ansible-role-proxy
