- hosts: client
  become: yes
  roles:
    - ansible-role-docker
    - ansible-role-java

- hosts: all
  become: yes
  roles:
    - ansible-role-consul
    - ansible-role-nomad
#    - ansible-role-dnsmasq

- hosts: server
  become: yes
  roles:
    - ansible-role-proxy
