---

- name: Ensure nginx-repository is installed
  yum: name=epel-release state=installed

- name: Ensure nginx is installed
  yum: name=nginx state=installed

- name: Fix allow proxy nginx to different port
  command: /usr/sbin/setsebool -P httpd_can_network_connect true

- name: Ensure nginx service is started and enabled on boot
  service: name=nginx state=started enabled=yes






- name: Ensure unzip is installed (required by unarchive module)
  yum: name=unzip state=installed

- name: Ensure wget is installed
  yum: name=wget state=installed

- name: Descargamos consul template
  get_url: >
    url={{ consul_template_url }}
    dest=/tmp/consul-template.zip

- name: Unzip Consul-template to installation directory
  command: unzip /tmp/consul-template.zip -d {{ consul_template_dir }}
  args:
    creates: "{{ consul_template_dir }}"

- name: Add consul-template config nginx upstreams
  template: >
    src=nginx-consultemplate-upstreams.conf
    dest={{ consul_template_dir }}/nginx-consultemplate-upstreams.conf

- name: Add consul-template config nginx endpoints
  template: >
    src=nginx-consultemplate-endpoints.conf
    dest={{ consul_template_dir }}/nginx-consultemplate-endpoints.conf

- name: If consul-template.service configuration already exists, remove it
  file: >
    state=absent
    path=/etc/systemd/system/consul-template.service

- name: Create consul-template.service configuration
  template: >
    src=consul-template.service.j2
    dest=/etc/systemd/system/consul-template.service
    owner=root
    group=root
    mode=0644
  notify: restart consul-template

- name: Ensure Consul-template service is started and enabled on boot
  service: name=consul-template state=started enabled=yes
